/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petUpdatePet } from "../../funcs/petUpdatePet.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.PetInput$inboundSchema,
};

export const tool$petUpdatePet: ToolDefinition<typeof args> = {
  name: "pet-update-pet",
  description: `Update an existing pet`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petUpdatePet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
