/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petUpdatePetWithForm } from "../../funcs/petUpdatePetWithForm.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdatePetWithFormRequest$inboundSchema,
};

export const tool$petUpdatePetWithForm: ToolDefinition<typeof args> = {
  name: "pet-update-pet-with-form",
  description: `Updates a pet in the store with form data`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petUpdatePetWithForm(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
