/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { userCreateUsersWithArrayInput } from "../../funcs/userCreateUsersWithArrayInput.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.array(components.User$inboundSchema),
};

export const tool$userCreateUsersWithArrayInput: ToolDefinition<typeof args> = {
  name: "user-create-users-with-array-input",
  description: `Creates list of users with given input array`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await userCreateUsersWithArrayInput(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
