/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petAddPet } from "../funcs/petAddPet.js";
import { petAddPetRaw } from "../funcs/petAddPetRaw.js";
import { petDeletePet } from "../funcs/petDeletePet.js";
import {
  FindPetsByStatusAcceptEnum,
  petFindPetsByStatus,
} from "../funcs/petFindPetsByStatus.js";
import {
  FindPetsByTagsAcceptEnum,
  petFindPetsByTags,
} from "../funcs/petFindPetsByTags.js";
import { GetPetByIdAcceptEnum, petGetPetById } from "../funcs/petGetPetById.js";
import { petUpdatePet } from "../funcs/petUpdatePet.js";
import { petUpdatePetRaw } from "../funcs/petUpdatePetRaw.js";
import { petUpdatePetWithForm } from "../funcs/petUpdatePetWithForm.js";
import { petUploadFile } from "../funcs/petUploadFile.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { FindPetsByStatusAcceptEnum } from "../funcs/petFindPetsByStatus.js";

export { FindPetsByTagsAcceptEnum } from "../funcs/petFindPetsByTags.js";

export { GetPetByIdAcceptEnum } from "../funcs/petGetPetById.js";

export class Pet extends ClientSDK {
  /**
   * Add a new pet to the store
   */
  async addPet(
    request: components.PetInput,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(petAddPet(
      this,
      request,
      options,
    ));
  }

  /**
   * Add a new pet to the store
   */
  async addPetRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(petAddPetRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing pet
   */
  async updatePet(
    request: components.PetInput,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(petUpdatePet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing pet
   */
  async updatePetRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(petUpdatePetRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Finds Pets by status
   *
   * @remarks
   * Multiple status values can be provided with comma separated strings
   */
  async findPetsByStatus(
    request: operations.FindPetsByStatusRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: FindPetsByStatusAcceptEnum;
    },
  ): Promise<operations.FindPetsByStatusResponse> {
    return unwrapAsync(petFindPetsByStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Finds Pets by tags
   *
   * @remarks
   * Muliple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async findPetsByTags(
    request: operations.FindPetsByTagsRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: FindPetsByTagsAcceptEnum;
    },
  ): Promise<operations.FindPetsByTagsResponse> {
    return unwrapAsync(petFindPetsByTags(
      this,
      request,
      options,
    ));
  }

  /**
   * Find pet by ID
   *
   * @remarks
   * Returns a single pet
   */
  async getPetById(
    security: operations.GetPetByIdSecurity,
    request: operations.GetPetByIdRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetPetByIdAcceptEnum },
  ): Promise<operations.GetPetByIdResponse | undefined> {
    return unwrapAsync(petGetPetById(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Updates a pet in the store with form data
   */
  async updatePetWithForm(
    request: operations.UpdatePetWithFormRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(petUpdatePetWithForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Deletes a pet
   */
  async deletePet(
    request: operations.DeletePetRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(petDeletePet(
      this,
      request,
      options,
    ));
  }

  /**
   * uploads an image
   */
  async uploadFile(
    request: operations.UploadFileRequest,
    options?: RequestOptions,
  ): Promise<components.ApiResponse> {
    return unwrapAsync(petUploadFile(
      this,
      request,
      options,
    ));
  }
}
