/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PlaceOrderResponse = components.Order | Uint8Array | string;

/** @internal */
export const PlaceOrderResponse$inboundSchema: z.ZodType<
  PlaceOrderResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Order$inboundSchema, b64$.zodInbound]);

/** @internal */
export type PlaceOrderResponse$Outbound =
  | components.Order$Outbound
  | Uint8Array;

/** @internal */
export const PlaceOrderResponse$outboundSchema: z.ZodType<
  PlaceOrderResponse$Outbound,
  z.ZodTypeDef,
  PlaceOrderResponse
> = z.union([components.Order$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PlaceOrderResponse$ {
  /** @deprecated use `PlaceOrderResponse$inboundSchema` instead. */
  export const inboundSchema = PlaceOrderResponse$inboundSchema;
  /** @deprecated use `PlaceOrderResponse$outboundSchema` instead. */
  export const outboundSchema = PlaceOrderResponse$outboundSchema;
  /** @deprecated use `PlaceOrderResponse$Outbound` instead. */
  export type Outbound = PlaceOrderResponse$Outbound;
}

export function placeOrderResponseToJSON(
  placeOrderResponse: PlaceOrderResponse,
): string {
  return JSON.stringify(
    PlaceOrderResponse$outboundSchema.parse(placeOrderResponse),
  );
}

export function placeOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlaceOrderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlaceOrderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaceOrderResponse' from JSON`,
  );
}
